name: Build and Deploy to DigitalOcean

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy to DigitalOcean
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.DO_DROPLET_IP }}
                  username: ${{ secrets.DO_USERNAME }}
                  key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
                  script: |
                      chmod +x /root/donniebot/scripts/deploy.sh
                      /root/donniebot/scripts/deploy.sh
